sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3171
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9tyNrEyqNFRywsgh9T
    access-key-secret: gRrhH9Be2jhOOLL9iYW2isu7HWCcJu
    bucket-name: sky-lmk
  redis:
    host: localhost
    port: 6379
    password: 3171
    database: 10
  wechat:
      app-id: wx214d7d4510c90fa5
      app-secret: a3fd961c56f8d2956cb3b57bd7d750f0
  shop:
    address: 新疆维吾尔自治区乌鲁木齐市沙依巴克区南昌路42号家属区四合院208号
  baidu:
    ak: TXgd1wJSGoF0D47dsXe1eoDG5uY1exsz